routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\BooksController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::resource('books', BooksController::class)->except('destroy');
    Route::get('books/{id}/destroy', [BooksController::class, 'destroy'])->name('books.destroy');

});



require __DIR__.'/auth.php';

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * @property int    $id
 * @property int    $idUser
 * @property Date   $soldDate
 * @property string $comments
 * @property string $photo
 * @property string $publisher
 * @property string $idModule
 */

class Book extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'books';

    /**
     * The primary key for the model.
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = [
        'idUser', 'soldDate', 'comments', 'photo', 'status', 'pages', 'price', 'publisher', 'idModule'
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'int', 'idUser' => 'int', 'soldDate' => 'date', 'comments' => 'string', 'photo' => 'string', 'publisher' => 'string', 'idModule' => 'string'
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'soldDate'
    ];

    /**
     * Indicates if the model should be timestamped.
     *
     * @var boolean
     */
    public $timestamps = false;

    // Scopes...

    // Functions ...

    // Relations ...
    public function Module(){
        return $this->belongsTo(Module::class,'idModule','code'); 
    } 
}

app/Http/Controllers/Api/BookController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Book;
use Illuminate\Http\Request;
use App\Http\Resources\BookResource;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return BookResource::collection(Book::all());
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $book = new Book;
        $book->idUser = $request->idUser;
        $book->idModule = $request->idModule;
        $book->publisher = $request->publisher;
        $book->price = $request->price;
        $book->pages = $request->pages;
        $book->status = $request->status;
        $book->photo = $request->photo;
        $book->comments = $request->comments;
        $book->soldDate = $request->soldDate;

        $book->save();

        return response()->json($book, 201);
    }

    /**
     * Display the specified resource.
     */
    public function show(Book $book)
    {
        return new BookResource($book);

    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Book $book)
    {
        $book->idUser = $request->idUser;
        $book->idModule = $request->idModule;
        $book->publisher = $request->publisher;
        $book->price = $request->price;
        $book->pages = $request->pages;
        $book->status = $request->status;
        $book->photo = $request->photo;
        $book->comments = $request->comments;
        $book->soldDate = $request->soldDate;
        $book->save();
        return response()->json($book);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Book $book)
    {
        $book->delete();
        return response()->json(null, 204);
    }
}

app/Http/Controllers/BooksController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Book;
use Illuminate\Support\Facades\Auth;


use App\Models\Module;

class BooksController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $books = Book::paginate(10);
        return view('books.index', ['books' => $books]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        
        $modules = Module::all();
        return view('books.create', compact('modules'));
    }

    /**
     * Store a newly created resource in storage.
     */
    /*public function store(Request $request){
    
            // Obtener el archivo de imagen del formulario
            $imageFile = $request->photo;
    
            // Generar un nombre único para la imagen
            $fileName = time() . '.' . $imageFile->getClientOriginalExtension();
    
            // Guardar la imagen en el almacenamiento de Laravel
        
            $imageFile->move(storage_path().'/app/public/images/', $fileName);
            
    
        $book = new Book($request->all());
        $book->idUser = Auth::user()->id;
        $book->photo = $fileName;
        $book->save();
        return redirect()->route('books.index');
    }*/

    public function store(Request $request){

    $validatedData = $request->validate([
        'publisher' => 'required|max:50',
        'price' => 'required',
        'pages' => 'required|numeric',
        'comments' => 'required',
        'status' => 'required',
        'idModule' => 'required'
    ]);

    if ($request->hasFile('photo')) {
        $imageFile = $request->file('photo');

        $fileName = time() . '.' . $imageFile->getClientOriginalExtension();

        $imageFile->move(storage_path('/app/public/images/'), $fileName);

        $book = new Book($validatedData);
        $book->idUser = Auth::user()->id;
        $book->photo = $fileName;
        $book->save();

        return redirect()->route('books.index');
    }else{
        $book = new Book($validatedData);
        $book->idUser = Auth::user()->id;
        $book->save();

        return redirect()->route('books.index');
    }

    return back()->withErrors(['photo' => 'Se requiere una imagen.'])->withInput();
}


    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $book= Book::findOrFail($id);
        return view('books.show', compact('book'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $book = Book::findOrFail($id);
        $modules = Module::all();
        return view('books.edit', compact('book', 'modules'));
    }

    /**
     * Update the specified resource in storage.
     */
    /*public function update(Request $request, string $id)
    {

            // Obtener el archivo de imagen del formulario
            $imageFile = $request->photo;
    
            // Generar un nombre único para la imagen
            $fileName = time() . '.' . $imageFile->getClientOriginalExtension();
    
            // Guardar la imagen en el almacenamiento de Laravel
            
        
            $imageFile->move(storage_path().'/app/public/images/', $fileName);
            
    

        $book = Book::findOrFail($id);
        $book->update($request->all());
        $book->photo = $fileName;
        $book->save();
        return redirect()->route('books.index');
    }*/

    public function update(Request $request, string $id) {
        $validatedData = $request->validate([
            'publisher' => 'required|max:50',
            'price' => 'required',
            'pages' => 'required|numeric',
            'comments' => 'required',
            'status' => 'required',
            'idModule' => 'required'
        ]);

        if ($request->hasFile('photo')) {
            $imageFile = $request->file('photo');

            $fileName = time() . '.' . $imageFile->getClientOriginalExtension();

            $imageFile->move(storage_path('/app/public/images/'), $fileName);

            $book = Book::findOrFail($id);
            $book->update($validatedData);
            $book->photo = $fileName;
            $book->save();
            return redirect()->route('books.index');

        }else{

            $book = Book::findOrFail($id);
            $book->update($validatedData);
            $book->save();
            return redirect()->route('books.index');
        }

        return back()->withErrors(['photo' => 'Se requiere una imagen.'])->withInput();
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $book = Book::find($id);
        $book->delete();
        return redirect()->route('books.index');
    }
}

resources/views/books/create.blade.php
@extends("layouts.plantilla")
@section("contenido")
    <section class="col-md-12">
        <div class="container  d-flex justify-content-center">
            <div class="row">
                <div class="col-md-6">
                    <h1 class="display-4">New Product</h1>
                </div>
            </div>


            <div class="row">
                <form method="post" action="{{ route('books.store')}}" enctype = "multipart/form-data" >
                    @csrf
                    @method('POST')
                    <!-- Publisher input -->
                    <div class="form-outline mb-4">
                        <input type="text" name="publisher" id="formRegister1" class="form-control" value="{{old('publisher')}}" />
                        <label class="form-label" for="formRegister1">Publisher</label>
                    </div>
@error('publisher')
    <span class="text-danger" style="color: red">El publisher es demasiado largo o está vacío</span>
@enderror
                    <!-- Price input -->
                    <div class="form-outline mb-4">
                        <input type="number" name="price" id="formRegister2" class="form-control" value="{{old('price')}}" />
                        <label class="form-label" for="formRegister2">Price</label>
                    </div>
@error('price')
    <span class="text-danger" style="color: red">El precio tiene que ser númerico y no puede estar vacío</span>
@enderror
                    <!-- Pages input -->
                    <div class="form-outline mb-4">
                        <input type="number" name="pages" id="formRegister3" class="form-control" value="{{old('pages')}}" />
                        <label class="form-label" for="formRegister3">Pages</label>
                    </div>
@error('pages')
    <span class="text-danger" style="color: red">Las tiene que ser númerico y no puede estar vacío</span>
@enderror
                    <!-- Status input -->
                    <div class="form-outline mb-4">
                        <select name="status" value="{{old('status')}}" >   
                            <option value="new">New</option>
                            <option value="good">Good</option>
                            <option value="used">Used</option>
                            <option value="bad">Bad</option>
                        </select>
                        <br>
                        <label class="form-label" for="formRegister3">Status</label>
                    </div>
                    <!-- Photo input -->
                    <div class="form-outline mb-4">
                    <input id="photo" name="photo" type="file" value="{{old('photo')}}" >
                        <br>
                        <label class="form-label" for="formRegister3">Photo</label>
                    </div>
                    <!-- Comments input -->
                    <div class="form-outline mb-4">
                        <input type="text" name="comments" id="formRegister6" class="form-control" value="{{old('comments')}}" />
                        <label class="form-label" for="formRegister3">Comments</label>
                    </div>
@error('comments')
    <span class="text-danger" style="color: red">El comentario no puede estar vacío</span>
@enderror
                    <!-- Comments input -->
                    <div class="form-outline mb-4">
                        <select name="idModule" value="{{old('idModule')}}" >
                            @foreach ($modules as $modulos) {
                                <option value="{{$modulos->code}}">{{$modulos->cliteral}}</option>
                            }
                            @endforeach
                        </select>
                        <br>
                        <label class="form-label" for="formRegister3">Module</label>
                    </div>
                    <!-- Submit button -->
                    <button type="submit" class="btn btn-primary btn-block">Add book</button>
                </form>
            </div>
        </div>
    </section>

@endsection

resources/views/books/edit.blade.php
@extends("layouts.plantilla")
@section("contenido")
    <section class="col-md-12">
        <div class="container  d-flex justify-content-center">
            <div class="row">
                <div class="col-md-6">
                    <h1 class="display-4">Edit Product</h1>
                </div>
            </div>
            <div class="row">
                <form method="post" action="{{ route('books.update', $book->id) }}" enctype="multipart/form-data" >
                    @csrf
                    @method('PUT')
                    <!-- Publisher input -->
                    <div class="form-outline mb-4">
                        <input type="text" name="publisher" id="formRegister1" class="form-control" value="<?=$book->publisher?>"/>
                        <label class="form-label" for="formRegister1">Publisher</label>
                    </div>
@error('publisher')
    <span class="text-danger" style="color: red">El publisher es demasiado largo o está vacío</span>
@enderror
                    <!-- Price input -->
                    <div class="form-outline mb-4">
                        <input type="number" name="price" id="formRegister2" class="form-control" value="<?=$book->price?>"/>
                        <label class="form-label" for="formRegister2">Price</label>
                    </div>
@error('price')
    <span class="text-danger" style="color: red">El precio tiene que ser númerico y no puede estar vacío</span>
@enderror                   
                    <!-- Pages input -->
                    <div class="form-outline mb-4">
                        <input type="number" name="pages" id="formRegister3" class="form-control" value="<?=$book->pages?>"/>
                        <label class="form-label" for="formRegister3">Pages</label>
                    </div>
@error('pages')
    <span class="text-danger" style="color: red">Las tiene que ser númerico y no puede estar vacío</span>
@enderror
                    <!-- Status input -->
                    <div class="form-outline mb-4">
                        <select name="status">   
                            <option value="new" <?= ($book->status === "new")?'selected':'' ?>>New</option>
                            <option value="good" <?= ($book->status === "good")?'selected':'' ?>>Good</option>
                            <option value="used" <?= ($book->status === "used")?'selected':'' ?>>Used</option>
                            <option value="bad" <?= ($book->status === "bad")?'selected':'' ?>>Bad</option>
                        </select>
                        <br>
                        <label class="form-label" for="formRegister3">Status</label>
                    </div>
                    <!-- Photo input -->
                    <div class="form-outline mb-4">
                    <input id="photo" name="photo" type="file">
                        <br>
                        <label class="form-label" for="formRegister3">{{ $book->photo }}</label>
                    </div>
                    <!-- Comments input -->
                    <div class="form-outline mb-4">
                        <input type="text" name="comments" id="formRegister6" class="form-control" value="<?=$book->comments?>"/>
                        <label class="form-label" for="formRegister3">Comments</label>
                    </div>
@error('comments')
    <span class="text-danger" style="color: red">El comentario no puede estar vacío</span>
@enderror
                    <!-- Module input -->
                    <div class="form-outline mb-4">
                        <select id="idModule" name="idModule">   
                            @foreach ($modules as $modulos) 
                                <option value="{{ $modulos->code }}" {{ ($modulos->code === $book->idModule)?'selected':'' }}> {{$modulos->cliteral }}</option>
                            @endforeach
                        </select>
                        <br>
                        <label class="form-label" for="formRegister3">Module</label>
                    </div>
                    <!-- Submit button -->
                    <button type="submit" class="btn btn-primary btn-block">Edit book</button>
                </form>
            </div>
        </div>
    </section>

@endsection

resources/views/books/index.blade.php
@extends("layouts.plantilla")
@section("contenido")
<header>
        <button><a href="{{route('books.create')}}">Subir producto</a></button>
    </header>
<table>
<tr><th style="text-align: center;">Id</th><th style="padding-left: 200px; text-align: center;">Module</th><th style="padding-left: 200px; text-align: center;">Publisher</th></tr>
@foreach ($books ??[] as $book) 
        <tr>
        <td>{{$book->id}}</td>
        <td style="padding-left: 100px;">{{$book->module->cliteral}}</td>
        <td style="padding-left: 200px;">{{$book->publisher}}</td>
       <td style="padding-left: 200px;"><a href="{{route('books.show',$book->id)}}"><button>Ver más</button></a></td>
        </tr>

@endforeach
</table>

{{ $books->links() }}

@endsection

resources/views/books/show.blade.php
@extends("layouts.plantilla")
@section("contenido")
    <table>
<tr><th style="text-align: center;">Photo</th>
    <th style="padding-left: 100px; text-align: center;">Module</th>
    <th style="padding-left: 100px; text-align: center;">Publisher</th>
    <th style="padding-left: 100px; text-align: center;">Price</th>
    <th style="padding-left: 100px; text-align: center;">Pages</th>
    <th style="padding-left: 100px; text-align: center;">Acciones</th></tr>


        <td><img src="{{ asset('/storage/images/' . $book->photo) }}"></td>
        <td style="padding-left: 75px;">{{$book->module->cliteral}}</td>
        <td style="padding-left: 75px;">{{$book->publisher}}</td>
        <td style="padding-left: 75px; text-align: center;">{{$book->price.'€'}}</td>
        <td style="padding-left: 75px; text-align: center;">{{$book->pages}}</td>
        <td style="padding-left: 100px;"><a href="{{route('books.destroy',$book->id)}}"><button>Borrar</button></a></td>
        <td style="padding-left: 10px;"><a href="{{route('books.edit',$book->id)}}"><button>Editar</button></a></td>
        </tr>

</table>

@endsection